#!/usr/bin/env bash
# lib/steps.sh — Install steps: venv, npm, dirs, docker, systemd, pm2, claude, webhook.
#
# Sourced by install.sh; do not execute directly.
# shellcheck shell=bash

step_venv() {
  log "$_S_STEP_VENV $BACKEND_DIR/venv"
  if [ ! -d "$BACKEND_DIR/venv" ]; then python3 -m venv "$BACKEND_DIR/venv"; fi

  # Bootstrap: pip-compile ve pip-sync için pip-tools'u regular pip ile kur
  log "$_S_STEP_PKG_BOOTSTRAP"
  "$BACKEND_DIR/venv/bin/pip" install --quiet --upgrade pip pip-tools

  # Seçili capability dosyalarını belirle
  local req_files cap_names=()
  mapfile -t req_files < <(_resolve_requirements)
  for f in "${req_files[@]}"; do cap_names+=( "$(basename "$f" .txt)" ); done
  log "$_S_STEP_PKG_COMPILE ${cap_names[*]}"

  # pip-compile: seçili dosyaları birleştir + tüm transitive dep'leri çöz → pinned file.
  # compiled.txt machine-specific, gitignored.
  local compiled="$BACKEND_DIR/requirements/compiled.txt"
  "$BACKEND_DIR/venv/bin/pip-compile" \
    --no-header --no-annotate --no-strip-extras \
    --output-file="$compiled" \
    "${req_files[@]}"

  # pip-sync: compiled.txt'e göre venv'i atomik senkronize et.
  # Eksik paketleri kurar; listede olmayan (devre dışı capability) paketleri kaldırır.
  log "$_S_STEP_PKG_SYNC ${cap_names[*]}"
  "$BACKEND_DIR/venv/bin/pip-sync" "$compiled"

  # sudo-mode: venv was created as root; service runs as $SUDO_USER and must
  # be able to read .pyc files etc.  Restore ownership.
  if [ "$EUID" -eq 0 ] && [ -n "${SUDO_USER:-}" ] && [ "$SUDO_USER" != "root" ]; then
    local _grp
    _grp="$(id -gn "$SUDO_USER" 2>/dev/null || echo "$SUDO_USER")"
    chown -R "$SUDO_USER:$_grp" "$BACKEND_DIR/venv" 2>/dev/null || true
  fi
  ok "$_S_STEP_VENV_DONE"
}


step_npm() {
  log "$_S_STEP_NPM $BRIDGE_DIR/node_modules"
  (cd "$BRIDGE_DIR" && npm install --silent)
  ok "$_S_STEP_NPM_DONE"
}


step_data_dirs() {
  log "$_S_STEP_DIRS"
  mkdir -p \
    "$ROOT_DIR/data/projects" \
    "$ROOT_DIR/data/media" \
    "$ROOT_DIR/data/claude_sessions" \
    "$ROOT_DIR/data/conv_history" \
    "$ROOT_DIR/outputs/logs" \
    "$ROOT_DIR/reports/done" \
    "$ROOT_DIR/research/done"

  # When run via sudo, dirs are owned by root — but services start as $SUDO_USER,
  # which then can't write to data/personal_agent.db etc.  Restore ownership.
  if [ "$EUID" -eq 0 ] && [ -n "${SUDO_USER:-}" ] && [ "$SUDO_USER" != "root" ]; then
    local _grp
    _grp="$(id -gn "$SUDO_USER" 2>/dev/null || echo "$SUDO_USER")"
    chown -R "$SUDO_USER:$_grp" \
      "$ROOT_DIR/data" "$ROOT_DIR/outputs" "$ROOT_DIR/reports" "$ROOT_DIR/research" \
      2>/dev/null || warn "  ↳ chown failed for data dirs (continuing)"
  fi
  ok "$_S_STEP_DIRS_DONE"
}


step_docker_group() {
  if ! command -v docker &>/dev/null; then return; fi
  if docker info &>/dev/null 2>&1; then
    ok "$_S_STEP_DOCKER_OK"; return
  fi
  if [ "$EUID" -eq 0 ]; then
    usermod -aG docker "$CURRENT_USER"
    ok "$_S_STEP_DOCKER_ADDED"
  else
    warn "$_S_STEP_DOCKER_WARN"
    warn "$_S_STEP_DOCKER_FIX $CURRENT_USER && newgrp docker"
  fi
}


step_docker_build() {
  if ! command -v docker &>/dev/null; then
    die "$_S_DOCKER_NOT_FOUND"
  fi
  if ! docker compose version &>/dev/null 2>&1; then
    die "$_S_DOCKER_COMPOSE_NOT_FOUND"
  fi

  # ── credentials.json pre-flight: Docker file mount requires source to be a file.
  # If it doesn't exist, Docker creates a directory — breaking claude CLI auth.
  local cred_file="$HOME/.claude/.credentials.json"
  if [ ! -f "$cred_file" ]; then
    mkdir -p "$HOME/.claude"
    echo "{}" > "$cred_file"
    warn "$_S_DOCKER_CRED_CREATED"
  else
    ok "$_S_DOCKER_CRED_OK"
  fi

  # Seçili capability dosyalarını belirle
  local req_files cap_names=()
  mapfile -t req_files < <(_resolve_requirements)
  for f in "${req_files[@]}"; do cap_names+=( "$(basename "$f" .txt)" ); done

  local caps_str="${cap_names[*]}"  # "core dev scheduler browser" gibi

  log "$_S_DOCKER_BUILD"
  log "$_S_DOCKER_BUILD_CAPS $caps_str"

  # docker-compose.override.yml yaz — build-arg olarak ilet
  log "$_S_DOCKER_OVERRIDE"
  cat > "$ROOT_DIR/docker-compose.override.yml" <<EOF
# Auto-generated by install.sh --docker — do not edit manually
# Re-run: bash install.sh --docker
services:
  99-api:
    build:
      args:
        CAPABILITIES: "${caps_str}"
EOF

  # Build
  log "$_S_DOCKER_BUILD_RUN"
  docker compose -f "$ROOT_DIR/docker-compose.yml" \
                 -f "$ROOT_DIR/docker-compose.override.yml" \
                 build

  # Up
  log "$_S_DOCKER_UP"
  docker compose -f "$ROOT_DIR/docker-compose.yml" \
                 -f "$ROOT_DIR/docker-compose.override.yml" \
                 up -d

  ok "$_S_DOCKER_BUILD_DONE"

  # ── Webhook auto-registration for ngrok/cloudflared proxy ─────────────────
  # Public URL is only known at runtime (ngrok starts inside the container).
  # Poll /health until public_url appears, then register the webhook.
  local _env_dst="$BACKEND_DIR/.env"
  local _proxy _messenger
  _proxy="$(_read_env_var "WEBHOOK_PROXY"  "$_env_dst")"
  _messenger="$(_read_env_var "MESSENGER_TYPE" "$_env_dst")"
  _messenger="${_messenger:-whatsapp}"

  if [[ "$_proxy" == "ngrok" || "$_proxy" == "cloudflared" ]]; then
    log "$_S_DOCKER_WAIT_URL"
    local _pub_url="" _retry=0 _health

    while [[ -z "$_pub_url" && $_retry -lt 45 ]]; do
      sleep 2
      _retry=$((_retry + 1))
      _health="$(curl -s --max-time 4 "http://localhost:${API_PORT}/health" 2>/dev/null || true)"
      [[ -n "$_health" ]] && _pub_url="$(_extract_json_field "$_health" "public_url")"
    done

    if [[ -n "$_pub_url" ]]; then
      ok "$_S_DOCKER_URL_FOUND: $_pub_url"
      if [[ "$_messenger" == "telegram" ]]; then
        local _tg_token _tg_secret _wh_url _wh_result
        _tg_token="$(_read_env_var "TELEGRAM_BOT_TOKEN"      "$_env_dst")"
        _tg_secret="$(_read_env_var "TELEGRAM_WEBHOOK_SECRET" "$_env_dst")"
        _wh_url="${_pub_url}/telegram/webhook"
        _wh_result="$(curl -s --max-time 8 -X POST \
          "https://api.telegram.org/bot${_tg_token}/setWebhook" \
          -H "Content-Type: application/json" \
          -d "{\"url\":\"${_wh_url}\",\"secret_token\":\"${_tg_secret}\",\"allowed_updates\":[\"message\",\"callback_query\"]}" \
          2>/dev/null || true)"
        if echo "$_wh_result" | grep -q '"ok":true'; then
          ok "$_S_WH_TG_REGISTERED: $_wh_url"
        else
          # Telegram API hatasını göster (örn. bad token, URL unreachable)
          local _wh_desc
          _wh_desc="$(_extract_json_field "$_wh_result" "description")"
          warn "  Webhook registration failed: ${_wh_desc:-unknown error}"
          echo "  Manual: curl -s -X POST 'https://api.telegram.org/bot${_tg_token}/setWebhook' -d 'url=${_wh_url}'"
        fi
      fi
    else
      warn "$_S_DOCKER_URL_TIMEOUT"
      # Kullanıcıya ngrok başlatma hatasını görmesi için yönlendir
      echo "  $_S_DOCKER_URL_DEBUG"
      echo "    docker compose logs 99-api 2>&1 | grep -iE 'ngrok|tunnel|webhook_proxy'"
    fi
  fi
}


render_template() {
  local template="$1" output="$2"
  python3 - "$template" "$output" \
    "$CURRENT_USER" "$ROOT_DIR" "$NODE_PATH" "$API_PORT" "$BRIDGE_PORT" <<'PYEOF'
import sys
tpl, out, user, root, node, api_port, bridge_port = sys.argv[1:]
with open(tpl) as f:
    t = f.read()
for placeholder, value in [
    ("{{USER}}", user), ("{{ROOT_DIR}}", root), ("{{NODE_PATH}}", node),
    ("{{API_PORT}}", api_port), ("{{BRIDGE_PORT}}", bridge_port),
]:
    t = t.replace(placeholder, value)
with open(out, "w") as f:
    f.write(t)
PYEOF
}


step_systemd() {
  if $NO_SYSTEMD; then log "$_S_STEP_SYSTEMD_SKIP"; return; fi
  if ! command -v systemctl &>/dev/null; then warn "$_S_STEP_SYSTEMD_MISSING"; return; fi

  log "$_S_STEP_SYSTEMD_RENDER"
  render_template "$SYSTEMD_DIR/personal-agent.service.template"        "$SYSTEMD_DIR/personal-agent.service"
  render_template "$SYSTEMD_DIR/personal-agent-bridge.service.template" "$SYSTEMD_DIR/personal-agent-bridge.service"
  ok "$_S_STEP_SYSTEMD_DONE $SYSTEMD_DIR/*.service"

  if [ "$EUID" -eq 0 ]; then
    cp "$SYSTEMD_DIR/personal-agent.service"        "$SYSTEM_UNIT_DIR/"
    cp "$SYSTEMD_DIR/personal-agent-bridge.service" "$SYSTEM_UNIT_DIR/"
    systemctl daemon-reload
    systemctl enable personal-agent.service personal-agent-bridge.service
    ok "$_S_STEP_SYSTEMD_INSTALLED"
    warn "$_S_STEP_SYSTEMD_START"
  else
    warn "$_S_STEP_SYSTEMD_NOROOT $SYSTEMD_DIR/"
    echo "      $_S_STEP_SYSTEMD_MANUAL"
    echo "        sudo cp $SYSTEMD_DIR/personal-agent*.service $SYSTEM_UNIT_DIR/"
    echo "        sudo systemctl daemon-reload"
    echo "        sudo systemctl enable --now personal-agent personal-agent-bridge"
  fi
}


step_pm2() {
  if ! $USE_PM2; then return; fi
  log "$_S_STEP_PM2_START"
  if ! command -v pm2 &>/dev/null; then
    npm install -g pm2 || die "npm install -g pm2 $_S_ERROR"
    ok "$_S_STEP_PM2_INSTALLED"
  else
    ok "$_S_STEP_PM2_EXISTS $(pm2 --version)"
  fi
  pm2 start "$ROOT_DIR/ecosystem.config.js"
  pm2 save
  pm2 startup || warn "$_S_STEP_PM2_STARTUP"
  ok "$_S_STEP_PM2_DONE"
}


step_claude_auth() {
  # Strict failure mode (default): abort install.sh on any auth error so the
  # user can't end up with a deployment that silently fails on first message.
  # Escape hatch: CLAUDE_AUTH_OPTIONAL=1 demotes errors to warnings — for CI
  # builds and advanced users who plan to authenticate later.
  local _strict=true
  [[ "${CLAUDE_AUTH_OPTIONAL:-}" == "1" ]] && _strict=false
  _auth_fail() { if $_strict; then die "$1"; else warn "$1"; warn "$_S_AUTH_OPTIONAL_HINT"; return 0; fi; }

  local env_dst="$BACKEND_DIR/.env"
  local api_key
  api_key="$(_read_env_var "ANTHROPIC_API_KEY" "$env_dst" 2>/dev/null || true)"
  if [[ -n "$api_key" && "$api_key" != *"FILL"* && "$api_key" != *"DOLDUR"* && "$api_key" != *"YOUR_"* ]]; then
    ok "$_S_AUTH_APIKEY"; return
  fi

  # Already authenticated? — empty {} (Docker pre-flight) doesn't count.
  if [[ -f "$HOME/.claude/.credentials.json" ]]; then
    local _cred_content
    _cred_content="$(tr -d ' \n\r\t' < "$HOME/.claude/.credentials.json" 2>/dev/null || echo "{}")"
    if [[ "$_cred_content" != "{}" && ${#_cred_content} -gt 5 ]]; then
      ok "$_S_AUTH_ALREADY"; return
    fi
  fi

  # Install claude CLI if missing — strict: hard fail so user fixes Node/npm.
  if ! command -v claude &>/dev/null; then
    if ! command -v npm &>/dev/null; then
      _auth_fail "$_S_AUTH_NPM_MISSING"; return
    fi
    log "$_S_AUTH_INSTALLING"
    if ! npm install -g @anthropic-ai/claude-code 2>&1 | tail -3; then
      _auth_fail "$_S_AUTH_INSTALL_FAIL"; return
    fi
    if ! command -v claude &>/dev/null; then
      # npm bin may not be on PATH yet — try to find it
      local _npm_bin="" _npm_prefix=""
      _npm_bin="$(npm bin -g 2>/dev/null || true)"
      if [[ -z "$_npm_bin" ]]; then
        _npm_prefix="$(npm prefix -g 2>/dev/null || true)"
        [[ -n "$_npm_prefix" ]] && _npm_bin="$_npm_prefix/bin"
      fi
      [[ -n "$_npm_bin" ]] && export PATH="$_npm_bin:$PATH"
      if ! command -v claude &>/dev/null; then
        _auth_fail "$_S_AUTH_INSTALL_FAIL"; return
      fi
    fi
    ok "$_S_AUTH_INSTALLED: $(claude --version 2>/dev/null | head -1 || echo 'installed')"
  fi

  # Run the OAuth flow.  The CLI either opens the default browser or prints
  # a fallback URL (headless / SSH).  Strict: non-zero exit aborts install.
  echo ""
  log "$_S_AUTH_NEEDED"
  echo "  $_S_AUTH_INSTR"
  echo ""
  if ! claude auth login; then
    _auth_fail "$_S_AUTH_FAIL_HARD"; return
  fi

  # Verify credentials were actually written (login can exit 0 even when
  # the user closes the browser early).
  local _cred_after
  _cred_after="$(tr -d ' \n\r\t' < "$HOME/.claude/.credentials.json" 2>/dev/null || echo "{}")"
  if [[ "$_cred_after" == "{}" || ${#_cred_after} -le 5 ]]; then
    _auth_fail "$_S_AUTH_EMPTY_CREDS"; return
  fi

  ok "$_S_AUTH_OK"
}


step_show_webhook_url() {
  local env_dst="$BACKEND_DIR/.env"
  [ ! -f "$env_dst" ] && return

  local messenger proxy public_url port
  messenger="$(_read_env_var "MESSENGER_TYPE" "$env_dst")"
  messenger="${messenger:-whatsapp}"
  proxy="$(_read_env_var "WEBHOOK_PROXY" "$env_dst")"
  proxy="${proxy:-none}"
  public_url="$(_read_env_var "PUBLIC_URL"   "$env_dst")"
  port="$(      _read_env_var "FASTAPI_PORT" "$env_dst")"
  port="${port:-$API_PORT}"

  echo ""
  echo "╔══════════════════════════════════════════════════════╗"
  echo "║  $_S_WH_TITLE"
  echo "╚══════════════════════════════════════════════════════╝"

  if [[ "$messenger" == "whatsapp" ]]; then
    local webhook_url
    if [[ -n "$public_url" ]]; then
      webhook_url="${public_url}/whatsapp/webhook"
    elif [[ "$proxy" == "none" ]]; then
      webhook_url="http://localhost:${port}/whatsapp/webhook"
    else
      webhook_url="<proxy URL — $_S_WH_WA_CONSOLE>"
    fi
    echo ""; echo "  $_S_WH_WA_URL"
    echo "  → $webhook_url"
    echo ""; echo "  $_S_WH_WA_CONSOLE"
    echo "  $_S_WH_WA_PATH"
    if [[ "$proxy" == "none" && -z "$public_url" ]]; then
      echo ""; warn "$_S_WH_WA_PROXY_WARN"
    fi

  elif [[ "$messenger" == "telegram" ]]; then
    local tg_token tg_secret
    tg_token="$( _read_env_var "TELEGRAM_BOT_TOKEN"      "$env_dst")"
    tg_secret="$(_read_env_var "TELEGRAM_WEBHOOK_SECRET" "$env_dst")"
    echo ""; echo "  $_S_WH_TG_SETUP"
    if [[ -n "$public_url" && -n "$tg_token" ]]; then
      # Static public URL (external proxy) — register now
      local _wh_url="${public_url}/telegram/webhook"
      local _wh_result
      _wh_result="$(curl -s --max-time 8 -X POST \
        "https://api.telegram.org/bot${tg_token}/setWebhook" \
        -H "Content-Type: application/json" \
        -d "{\"url\":\"${_wh_url}\",\"secret_token\":\"${tg_secret}\",\"allowed_updates\":[\"message\",\"callback_query\"]}" \
        2>/dev/null || true)"
      if echo "$_wh_result" | grep -q '"ok":true'; then
        ok "  $_S_WH_TG_REGISTERED: $_wh_url"
      else
        echo "  → $_wh_url"
        warn "  $_S_WH_TG_SETUP (manual): curl -s -X POST 'https://api.telegram.org/bot${tg_token}/setWebhook' -d 'url=${_wh_url}'"
      fi
    elif [[ "$proxy" == "ngrok" || "$proxy" == "cloudflared" ]]; then
      # Dynamic proxy — URL only known at runtime; Docker auto-registers on startup
      ok "  $_S_WH_TG_PROXY_RUNTIME"
    else
      echo "  → $_S_WH_TG_NO_URL"
      echo "    $_S_WH_TG_SETWEBHOOK"
    fi

  elif [[ "$messenger" == "cli" ]]; then
    echo ""; echo "  $_S_WH_CLI"
    echo "  $_S_WH_CLI_HINT"
  fi

  echo ""; echo "  $_S_WH_HEALTH"
  echo "  → curl -s http://localhost:${port}/health"
  echo "  → curl -s http://localhost:${BRIDGE_PORT}/health"
  echo ""
}

